name: Create Pull Request on DevOps Repository
on:
  workflow_run:
    workflows: ['Feature', 'Versioning', 'Release']
    types:
      - completed

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Checkout the target repository
        uses: actions/checkout@v2
        with:
          repository: ToxicToast/AzkabanV2-Flux
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target-repo

      - name: Update the version Gateway Service
        run: |
          cd target-repo
          sed -i "s/:${{ env.latest_tag }}/g" clusters/home/azkaban-v3/gateway/deployment.yaml
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-version-${{ env.latest_tag }}
          git add clusters/home/azkaban-v3/gateway/deployment.yaml
          git commit -m "Update version to ${{ env.latest_tag }}"
          

      - name: Update the version Auth Service
        run: |
          cd target-repo
          sed -i "s/:${{ env.latest_tag }}/g" clusters/home/azkaban-v3/auth/deployment.yaml
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-version-${{ env.latest_tag }}
          git add clusters/home/azkaban-v3/auth/deployment.yaml
          git commit -m "Update version to ${{ env.latest_tag }}"

      - name: Update the version Groups Service
        run: |
          cd target-repo
          sed -i "s/:${{ env.latest_tag }}/g" clusters/home/azkaban-v3/groups/deployment.yaml
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-version-${{ env.latest_tag }}
          git add clusters/home/azkaban-v3/groups/deployment.yaml
          git commit -m "Update version to ${{ env.latest_tag }}"

      - name: Update the version Users Service
        run: |
          cd target-repo
          sed -i "s/:${{ env.latest_tag }}/g" clusters/home/azkaban-v3/users/deployment.yaml
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-version-${{ env.latest_tag }}
          git add clusters/home/azkaban-v3/users/deployment.yaml
          git commit -m "Update version to ${{ env.latest_tag }}"

      - name: Update the version Webhooks Service
        run: |
          cd target-repo
          sed -i "s/:${{ env.latest_tag }}/g" clusters/home/azkaban-v3/webhooks/webhooks/deployment.yaml
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-version-${{ env.latest_tag }}
          git add clusters/home/azkaban-v3/webhooks/webhooks/deployment.yaml
          git commit -m "Update version to ${{ env.latest_tag }}"

      - name: Update the version Magpie Service
        run: |
          cd target-repo
          sed -i "s/:${{ env.latest_tag }}/g" clusters/home/azkaban-v3/webhooks/magpie/deployment.yaml
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-version-${{ env.latest_tag }}
          git add clusters/home/azkaban-v3/webhooks/magpie/deployment.yaml
          git commit -m "Update version to ${{ env.latest_tag }}"

      - name: Update the version Notification Service
        run: |
          cd target-repo
          sed -i "s/:${{ env.latest_tag }}/g" clusters/home/azkaban-v3/webhooks/notifications/deployment.yaml
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-version-${{ env.latest_tag }}
          git add clusters/home/azkaban-v3/webhooks/notifications/deployment.yaml
          git commit -m "Update version to ${{ env.latest_tag }}"

      - name: Update the version SSE Service
        run: |
          cd target-repo
          sed -i "s/:${{ env.latest_tag }}/g" clusters/home/azkaban-v3/webhooks/sse/deployment.yaml
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-version-${{ env.latest_tag }}
          git add clusters/home/azkaban-v3/webhooks/sse/deployment.yaml
          git commit -m "Update version to ${{ env.latest_tag }}"